package chocolate

var WhiteBlack = [8]uint8{
	246, // FOREGROUND_PRIMARY
	255, // FOREGROUND_SECONDARY
	232, // BACKGROUND_PRIMARY
	242, // BACKGROUND_SECONDARY
	15,  // FOREGROUND_HIGHLIGHT_PRIMARY
	15,  // FOREGROUND_HIGHLIGHT_SECONDARY
	237, // BACKGROUND_HIGHLIGHT_PRIMARY
	237, // BACKGROUND_HIGHLIGHT_SECONDARY
}
